#
# Make a copy of this file, change its name to database.yml and configure it with your own username and password below
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres # Change to your local pg username <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<----------
  password: postgres # Change to your local pg password <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<----------
development:
  <<: *default
  database: greetings-api_app_development
test:
  <<: *default
  database: greetings-api_app_test
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>